/* ===== multas.js — CBS4: módulo de multas + arranque ===== */
function vMultas(){const {currentYear,currentMonth}=state;const isAdmin=!state.isTransparencia;const mul=(appData.multas||[]).filter(m=>m.anio===currentYear&&m.mes===currentMonth);const pag=mul.filter(m=>m.estado==='Pagada').reduce((s,m)=>s+m.monto,0);
const gr=(uid,r,fc)=>{const s=new Date(fc);s.setMonth(s.getMonth()-6);return (appData.multas||[]).filter(m=>m.unidad_id===uid&&m.regla===r&&m.estado!=='Anulada'&&new Date(m.fecha_creacion)>=s).length>=2;};
return `<div class="page-title">Multas</div><div class="page-sub">Gestión de infracciones al reglamento</div>${monthTabs()}<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:14px;"><div class="stat-card" style="flex:none;padding:12px 18px;"><div class="stat-label">Recaudado Multas</div><div class="stat-value small">${fmt(pag)}</div></div>${isAdmin?`<button class="btn btn-danger" onclick="openNuevaMulta()">+ Nueva Multa</button>`:''}</div><div class="card">${mul.length===0?`<div style="text-align:center;padding:28px;color:var(--text3)">Sin multas en ${MESES[currentMonth]}</div>`:`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Dpto</th><th>Encargado</th><th>Regla</th><th>Monto</th><th>Estado</th><th style="width:200px;"></th></tr></thead><tbody>${mul.map(m=>{const dp=(appData.departamentos||[]).find(x=>x.id===m.unidad_id)||{};const rc=gr(m.unidad_id,m.regla,m.fecha_creacion);const be=m.estado==='Pagada'?'badge-green':(m.estado==='Anulada'?'badge-navy':'badge-red');return `<tr><td>${m.fecha_creacion}</td><td><strong style="color:var(--text)">${dp.numero||m.unidad_id}</strong></td><td>${dp.representante||'—'}</td><td><span class="badge badge-orange">${m.regla}</span>${rc?' <span title="Reincidente">⚠️</span>':''}</td><td><strong>${fmt(m.monto)}</strong></td><td><span class="badge ${be}">${m.estado}</span></td><td style="white-space:nowrap;"><button class="btn btn-ghost btn-sm" onclick="verMulta(${m.id})"></button><button class="btn btn-outline btn-sm" onclick="descargarVoucherMulta(${m.id})">📥</button>${m.estado!=='Pagada'&&isAdmin?`<button class="btn btn-success btn-sm" onclick="marcarPagadaMulta(${m.id})">💳</button>`:''}${isAdmin?`<button class="btn btn-warning btn-sm" onclick="editarMulta(${m.id})"></button><button class="btn btn-danger btn-sm" onclick="eliminarMulta(${m.id})"></button>`:''}</td></tr>`;}).join('')}</tbody></table></div>`}</div>${pag>0&&!state.isTransparencia?`<div style="font-size:11px;color:var(--text3);margin-top:10px;text-align:right;">✓ Este monto se incluye en "Recaudaciones Totales" del Dashboard</div>`:''}`;}

function openNuevaMulta(editId=null){let mu=editId?(appData.multas||[]).find(m=>m.id===editId):null;const {currentYear,currentMonth}=state;const fh=new Date().toISOString().split('T')[0];const ti=mu?`Editar Multa #${mu.id}`:`Nueva Multa — ${MESES[currentMonth]}`;const op=(appData.departamentos||[]).map(d=>`<option value="${d.id}" ${mu&&mu.unidad_id===d.id?'selected':''}>${d.numero} - ${d.representante||'Sin nombre'}</option>`).join('');
document.getElementById('modal-area').innerHTML=`<div class="modal-overlay open" onclick="if(event.target===this)closeModal()"><div class="modal" style="max-width:520px;"><div class="modal-title">${ti}</div><div class="form-row"><div><label class="fl">Departamento</label><select class="fi" id="nm-depto" onchange="cargarDatosDepto(this.value)">${op}<option value="">-- Seleccionar --</option></select></div></div><div class="form-row"><div><label class="fl">Encargado (auto)</label><input class="fi" id="nm-encargado" readonly value="${mu?mu.encargado:''}"/></div></div><div class="form-row form-row-2"><div><label class="fl">Regla</label><select class="fi" id="nm-regla"><option ${mu&&mu.regla==='Basura'?'selected':''}>Basura</option><option ${mu&&mu.regla==='Ruido'?'selected':''}>Ruido</option><option ${mu&&mu.regla==='Mascotas'?'selected':''}>Mascotas</option><option ${mu&&mu.regla==='Estacionamiento'?'selected':''}>Estacionamiento</option><option ${mu&&mu.regla==='Áreas comunes'?'selected':''}>Áreas comunes</option><option ${mu&&mu.regla==='Otro'?'selected':''}>Otro</option></select></div><div><label class="fl">Monto ($)</label><input class="fi" id="nm-monto" type="number" placeholder="0" value="${mu?mu.monto:''}"/></div></div><div class="form-row"><div><label class="fl">Motivo</label><textarea class="fi" id="nm-motivo" rows="2" maxlength="500">${mu?mu.motivo:''}</textarea></div></div><div class="form-row"><div><label class="fl">Fecha creación</label><input class="fi" type="date" value="${mu?mu.fecha_creacion:fh}" ${mu?'':'readonly'}/></div></div><div class="form-row"><label class="fl">Evidencia ${mu&&mu.evidencia_url?'(reemplazar)':'(opcional)'}</label><div class="file-drop" onclick="document.getElementById('nm-file').click()"> Adjuntar foto o acta</div><input type="file" id="nm-file" accept="image/*,application/pdf" style="display:none" onchange="previewFile(this,'nm-prev')"/><div id="nm-prev">${mu&&mu.evidencia_url?'<div class="file-preview">📄 <span class="file-name">Evidencia existente</span></div>':''}</div></div><div style="display:flex;gap:10px;margin-top:10px;"><button class="btn btn-danger" onclick="${editId?`actualizarMulta(${editId})`:'crearMulta()'}">${mu?'💾 Actualizar':'✅ Crear y descargar voucher'}</button><button class="btn btn-ghost" onclick="closeModal()">Cancelar</button></div></div></div>`;
if(mu&&mu.unidad_id){cargarDatosDepto(mu.unidad_id);}}

function cargarDatosDepto(id){const d=(appData.departamentos||[]).find(x=>x.id==id);document.getElementById('nm-encargado').value=d?d.representante||'':'';}

function crearMulta(){const {currentYear,currentMonth}=state;const uid=parseInt(document.getElementById('nm-depto').value);const r=document.getElementById('nm-regla').value;const m=parseInt(document.getElementById('nm-monto').value)||0;const mo=document.getElementById('nm-motivo').value.trim();const fc=document.querySelector('#nm-motivo').closest('.form-row').previousElementSibling.querySelector('input').value;if(!uid||!m||m<=0||!mo){showToast('Complete los campos requeridos','error');return;}const dp=(appData.departamentos||[]).find(d=>d.id===uid);const nm={id:Date.now(),unidad_id:uid,encargado:dp?dp.representante:'',regla:r,monto:m,motivo:mo,fecha_creacion:fc,evidencia_url:null,estado:'Notificada',anio:currentYear,mes:currentMonth,fecha_pago:null,creado_por:checkSession()||'admin'};const f=document.getElementById('nm-file');const pe=(a)=>{if(a)nm.evidencia_url=a;if(!appData.multas)appData.multas=[];appData.multas.push(nm);saveData();closeModal();renderView();showToast('Multa creada ✓','success');setTimeout(()=>descargarVoucherMulta(nm.id),300);};if(f&&f.files.length>0){compressImage(f.files[0],pe);}else{pe(null);}}

function actualizarMulta(id){const uid=parseInt(document.getElementById('nm-depto').value);const r=document.getElementById('nm-regla').value;const m=parseInt(document.getElementById('nm-monto').value)||0;const mo=document.getElementById('nm-motivo').value.trim();const fc=document.querySelector('#nm-motivo').closest('.form-row').previousElementSibling.querySelector('input').value;if(!uid||!m||m<=0||!mo){showToast('Complete los campos requeridos','error');return;}const mu=(appData.multas||[]).find(x=>x.id===id);if(!mu){showToast('Multa no encontrada','error');return;}const dp=(appData.departamentos||[]).find(d=>d.id===uid);mu.unidad_id=uid;mu.encargado=dp?dp.representante:'';mu.regla=r;mu.monto=m;mu.motivo=mo;mu.fecha_creacion=fc;const f=document.getElementById('nm-file');const pe=(a)=>{if(a)mu.evidencia_url=a;saveData();closeModal();renderView();showToast('Multa actualizada ✓','success');};if(f&&f.files.length>0){compressImage(f.files[0],pe);}else{pe(null);}}

function editarMulta(id){openNuevaMulta(id);}

function eliminarMulta(id){if(!confirm('¿Está seguro que desea ELIMINAR esta multa? Esta acción no se puede deshacer.'))return;const i=(appData.multas||[]).findIndex(m=>m.id===id);if(i===-1){showToast('Multa no encontrada','error');return;}appData.multas.splice(i,1);saveData();renderView();showToast('Multa eliminada','success');}

function descargarVoucherMulta(id){const mu=(appData.multas||[]).find(m=>m.id===id);if(!mu)return;const dp=(appData.departamentos||[]).find(d=>d.id===mu.unidad_id)||{};const fs=new Date(mu.fecha_creacion).toLocaleDateString('es-CL',{day:'2-digit',month:'long',year:'numeric'});const W=600,H=mu.evidencia_url?980:780;const cv=document.createElement('canvas');cv.width=W;cv.height=H;const ctx=cv.getContext('2d');
const dv=(dl)=>{ctx.fillStyle='#FFFFFF';ctx.fillRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,W,0);g.addColorStop(0,'#0E7490');g.addColorStop(1,'#2DD4BF');ctx.fillStyle=g;ctx.fillRect(0,0,W,160);dl(ctx,W/2-40,10,80,80);ctx.fillStyle='#FFFFFF';ctx.font='bold 15px Inter, Arial';ctx.textAlign='center';ctx.fillText('CONDOMINIO BOSQUES DEL SUR 4',W/2,175);ctx.fillStyle='#4B5563';ctx.font='500 13px Inter, Arial';ctx.fillText('Voucher válido como comprobante de pago',W/2,195);ctx.fillStyle=mu.estado==='Pagada'?'#10b981':'#EF4444';roundRect(ctx,W/2-50,210,100,32,16);ctx.fill();ctx.fillStyle='#FFFFFF';ctx.font='bold 14px Inter, Arial';ctx.fillText(mu.estado.toUpperCase(),W/2,232);ctx.strokeStyle='#E5E7EB';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(60,260);ctx.lineTo(W-60,260);ctx.stroke();let y=290;const LX=60;const RX=W-60;ctx.fillStyle='#111827';ctx.font='bold 13px Inter, Arial';ctx.textAlign='left';ctx.fillText('DEPARTAMENTO',LX,y);y+=30;ctx.fillStyle='#9CA3AF';ctx.font='12px Inter, Arial';ctx.fillText('N° Departamento',LX,y);ctx.fillStyle='#111827';ctx.font='bold 14px Inter, Arial';ctx.textAlign='right';ctx.fillText(dp.numero||mu.unidad_id,RX,y);y+=35;ctx.fillStyle='#9CA3AF';ctx.font='12px Inter, Arial';ctx.textAlign='left';ctx.fillText('Encargado',LX,y);ctx.fillStyle='#111827';ctx.font='bold 14px Inter, Arial';ctx.textAlign='right';ctx.fillText(mu.encargado||'—',RX,y);y+=45;ctx.strokeStyle='#E5E7EB';ctx.beginPath();ctx.moveTo(LX,y);ctx.lineTo(RX,y);ctx.stroke();y+=25;ctx.fillStyle='#111827';ctx.font='bold 13px Inter, Arial';ctx.textAlign='left';ctx.fillText('DETALLE DE INFRACCIÓN',LX,y);y+=30;ctx.fillStyle='#9CA3AF';ctx.font='12px Inter, Arial';ctx.fillText('Regla infringida',LX,y);ctx.fillStyle='#111827';ctx.font='bold 14px Inter, Arial';ctx.textAlign='right';ctx.fillText(mu.regla,RX,y);y+=35;ctx.fillStyle='#9CA3AF';ctx.font='12px Inter, Arial';ctx.textAlign='left';ctx.fillText('Motivo',LX,y);ctx.fillStyle='#111827';ctx.font='13px Inter, Arial';ctx.textAlign='right';(mu.motivo.match(/.{1,60}/g)||[]).forEach(l=>{ctx.fillText(l,RX,y);y+=20;});y+=15;ctx.fillStyle='#9CA3AF';ctx.font='12px Inter, Arial';ctx.textAlign='left';ctx.fillText('Fecha creación',LX,y);ctx.fillStyle='#111827';ctx.font='bold 14px Inter, Arial';ctx.textAlign='right';ctx.fillText(fs,RX,y);y+=45;ctx.strokeStyle='#E5E7EB';ctx.beginPath();ctx.moveTo(LX,y);ctx.lineTo(RX,y);ctx.stroke();y+=25;ctx.fillStyle='#111827';ctx.font='bold 13px Inter, Arial';ctx.textAlign='left';ctx.fillText('MONTO',LX,y);y+=30;ctx.fillStyle='#10b981';ctx.font='bold 28px Inter, Arial';ctx.textAlign='right';ctx.fillText(fmt(mu.monto),RX,y);y+=60;
const fin=()=>{ctx.fillStyle='#9CA3AF';ctx.font='11px Inter, Arial';ctx.textAlign='center';ctx.fillText('Documento generado automáticamente · Condominio Bosques del Sur 4',W/2,H-40);ctx.fillText('ID Multa: #'+mu.id,W/2,H-22);const url=cv.toDataURL('image/jpeg',0.95);lastVoucher={img:url,tipo:'multa',depto:dp,multa:mu};lastDownload={url:url,filename:'Multa_Depto'+(dp.numero||mu.unidad_id)+'_'+mu.fecha_creacion+'.jpg'};mostrarVoucherMulta(url,mu,dp);};
if(mu.evidencia_url){ctx.strokeStyle='#E5E7EB';ctx.beginPath();ctx.moveTo(LX,y);ctx.lineTo(RX,y);ctx.stroke();y+=25;ctx.fillStyle='#111827';ctx.font='bold 13px Inter, Arial';ctx.textAlign='left';ctx.fillText('EVIDENCIA ADJUNTA',LX,y);y+=30;const im=new Image();im.onload=function(){const iw=400,ih=250,ix=(W-iw)/2;ctx.drawImage(im,ix,y,iw,ih);fin();};im.onerror=fin;im.src=mu.evidencia_url.data||mu.evidencia_url;}else{fin();}};
const fb=(ctx,x,y,w,h)=>{ctx.fillStyle='#F1F5F9';ctx.fillRect(x,y,w,h);ctx.fillStyle='#0E7490';ctx.font='bold 16px Arial';ctx.textAlign='center';ctx.fillText('CBS4',x+w/2,y+h/2+6);};
const img=new Image();img.crossOrigin='Anonymous';img.src=LOGO_SRC;let shown=false;
const sv=(fn)=>{if(shown)return;shown=true;const url=dv(fn||fb);if(url){lastVoucher={img:url,tipo:'multa',depto:dp,multa:mu};lastDownload={url:url,filename:'Multa_Depto'+(dp.numero||mu.unidad_id)+'_'+mu.fecha_creacion+'.jpg'};mostrarVoucherMulta(url,mu,dp);}else showToast('Error generando imagen','error');};
img.onload=()=>sv((ctx,x,y,w,h)=>{ctx.drawImage(img,x,y,w,h);});
img.onerror=()=>sv(fb);setTimeout(()=>sv(fb),1500);}

function mostrarVoucherMulta(img,mu,dp){document.getElementById('modal-area').innerHTML=`<div class="modal-overlay open" onclick="if(event.target===this)closeModal()"><div class="modal" style="max-width:560px;"><div class="modal-title">🧾 Voucher de Multa</div><div class="holo-wrap" style="margin-bottom:16px;"><img src="${img}" style="width:100%;border-radius:10px;border:1px solid var(--border);"/></div><div style="display:flex;gap:8px;flex-wrap:wrap;"><button class="btn btn-danger" onclick="descargarUltimo()"> Descargar JPG</button><button class="btn btn-success" onclick="compartirUltimoVoucher()"> Compartir por WhatsApp</button><button class="btn btn-ghost" onclick="closeModal()">Cerrar</button></div></div></div>`;}

function verMulta(id){const m=(appData.multas||[]).find(x=>x.id===id);if(!m)return;const dp=(appData.departamentos||[]).find(d=>d.id===m.unidad_id)||{};document.getElementById('modal-area').innerHTML=`<div class="modal-overlay open" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-title">Detalle de Multa #${m.id}</div><div style="font-size:13px;line-height:1.8;"><strong>Departamento:</strong> ${dp.numero||m.unidad_id} - ${m.encargado||'—'}<br><strong>Regla:</strong> ${m.regla}<br><strong>Motivo:</strong> ${m.motivo}<br><strong>Fecha:</strong> ${m.fecha_creacion}<br><strong>Monto:</strong> ${fmt(m.monto)}<br><strong>Estado:</strong> <span class="badge ${m.estado==='Pagada'?'badge-green':'badge-red'}">${m.estado}</span><br>${m.evidencia_url?`<strong>Evidencia:</strong> <button class="btn btn-ghost btn-sm" onclick="verArchivoMulta(${m.id})">📎 Ver adjunto</button><br>`:''}</div><div style="display:flex;gap:10px;margin-top:16px;flex-wrap:wrap;"><button class="btn btn-outline" onclick="descargarVoucherMulta(${m.id})">📥 Voucher</button>${m.estado!=='Pagada'&&!state.isTransparencia?`<button class="btn btn-success" onclick="marcarPagadaMulta(${m.id})">💳 Marcar Pagada</button>`:''}${!state.isTransparencia?`<button class="btn btn-warning" onclick="closeModal();editarMulta(${m.id})">✎ Editar</button><button class="btn btn-danger" onclick="eliminarMulta(${m.id})">✕ Eliminar</button>`:''}<button class="btn btn-ghost" onclick="closeModal()">Cerrar</button></div></div></div>`;}

function verArchivoMulta(id){const m=(appData.multas||[]).find(x=>x.id===id);if(!m||!m.evidencia_url)return;lastDownload={url:m.evidencia_url.data,filename:'Evidencia_Multa_'+m.id+'.jpg'};const ii=m.evidencia_url.type&&m.evidencia_url.type.startsWith('image/');document.getElementById('modal-area').innerHTML=`<div class="modal-overlay open" onclick="if(event.target===this)closeModal()"><div class="modal" style="max-width:580px;"><div class="modal-title">📎 Evidencia</div>${ii?`<img src="${m.evidencia_url.data}" style="width:100%;border-radius:8px;margin-bottom:12px"/>`:'<div style="padding:20px;text-align:center;color:var(--text3)">📄 Archivo adjunto</div>'}<div style="display:flex;gap:8px;"><button class="btn btn-primary" onclick="descargarUltimo()">⬇ Descargar</button><button class="btn btn-ghost" onclick="closeModal()" style="flex:1;">Cerrar</button></div></div></div>`;}

function marcarPagadaMulta(id){if(!confirm('¿Marcar esta multa como PAGADA?'))return;const m=(appData.multas||[]).find(x=>x.id===id);if(!m)return;m.estado='Pagada';m.fecha_pago=new Date().toISOString().split('T')[0];saveData();renderView();showToast('Multa marcada como pagada ✓','success');}

/* ===== ARRANQUE DE LA APP (con anti-bloqueo) ===== */
document.addEventListener('DOMContentLoaded', async () => {
document.getElementById('logo-login').src=LOGO_SRC;
document.getElementById('topbar-logo').src=LOGO_SRC;
initFirebase();
initParticles();
const su=checkSession();
if(su&&ADMINS.some(a=>a.u===su)){state.loggedIn=true;state.isTransparencia=false;}
const p=new URLSearchParams(window.location.search);
if(p.get('vista')==='transparencia'){state.isTransparencia=true;state.loggedIn=false;state.currentView='reportes';}
setTimeout(()=>{const ov=document.getElementById('loading-overlay');if(ov&&ov.style.display!=='none'){ov.style.display='none';if(state.loggedIn||state.isTransparencia){showApp();}else{const ls=document.getElementById('login-screen');if(ls){ls.style.display='flex';renderLoginScreen();}}}},6000);
if(!(state.loggedIn||state.isTransparencia)){renderLoginScreen();}
});